// <auto-generated />
using System;
using System.Text.Json;
using MGF.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MGF.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215075210_Phase1_01_Lookups")]
    partial class Phase1_01_Lookups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("activity_ops", b =>
                {
                    b.Property<string>("op_key")
                        .HasColumnType("text")
                        .HasColumnName("op_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("op_key");

                    b.HasIndex("created_at");

                    b.HasIndex("op_key");

                    b.ToTable("activity_ops", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_ops_0", "op_key ~ '^[a-z0-9_.-]+$'");
                        });
                });

            modelBuilder.Entity("activity_priorities", b =>
                {
                    b.Property<string>("priority_key")
                        .HasColumnType("text")
                        .HasColumnName("priority_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("priority_key");

                    b.HasIndex("created_at");

                    b.HasIndex("priority_key");

                    b.ToTable("activity_priorities", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_priorities_0", "priority_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("activity_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("activity_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("activity_topics", b =>
                {
                    b.Property<string>("topic_key")
                        .HasColumnType("text")
                        .HasColumnName("topic_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("topic_key");

                    b.HasIndex("created_at");

                    b.HasIndex("topic_key");

                    b.ToTable("activity_topics", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_topics_0", "topic_key ~ '^[a-z0-9_.-]+$'");
                        });
                });

            modelBuilder.Entity("booking_phases", b =>
                {
                    b.Property<string>("phase_key")
                        .HasColumnType("text")
                        .HasColumnName("phase_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("phase_key");

                    b.HasIndex("created_at");

                    b.HasIndex("phase_key");

                    b.ToTable("booking_phases", null, t =>
                        {
                            t.HasCheckConstraint("CK_booking_phases_0", "phase_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("booking_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("booking_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_booking_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("client_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("client_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_client_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("client_types", b =>
                {
                    b.Property<string>("type_key")
                        .HasColumnType("text")
                        .HasColumnName("type_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("type_key");

                    b.HasIndex("created_at");

                    b.HasIndex("type_key");

                    b.ToTable("client_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_client_types_0", "type_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("currencies", b =>
                {
                    b.Property<string>("currency_code")
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<short?>("minor_units")
                        .HasColumnType("smallint")
                        .HasColumnName("minor_units");

                    b.Property<string>("symbol")
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("currency_code");

                    b.HasIndex("created_at");

                    b.HasIndex("currency_code");

                    b.ToTable("currencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_currencies_0", "currency_code ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_currencies_1", "minor_units IS NULL OR minor_units BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("data_profiles", b =>
                {
                    b.Property<string>("profile_key")
                        .HasColumnType("text")
                        .HasColumnName("profile_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("profile_key");

                    b.HasIndex("created_at");

                    b.HasIndex("profile_key");

                    b.ToTable("data_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_data_profiles_0", "profile_key IN ('real','dummy','fixture')");
                        });
                });

            modelBuilder.Entity("deliverable_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("deliverable_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_deliverable_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("delivery_methods", b =>
                {
                    b.Property<string>("method_key")
                        .HasColumnType("text")
                        .HasColumnName("method_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("method_key");

                    b.HasIndex("created_at");

                    b.HasIndex("method_key");

                    b.ToTable("delivery_methods", null, t =>
                        {
                            t.HasCheckConstraint("CK_delivery_methods_0", "method_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("host_keys", b =>
                {
                    b.Property<string>("host_key")
                        .HasColumnType("text")
                        .HasColumnName("host_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("host_type_key")
                        .HasColumnType("text")
                        .HasColumnName("host_type_key");

                    b.Property<JsonElement?>("metadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("host_key");

                    b.HasIndex("created_at");

                    b.HasIndex("host_key");

                    b.ToTable("host_keys", null, t =>
                        {
                            t.HasCheckConstraint("CK_host_keys_0", "host_key ~ '^[a-z0-9_]+$'");

                            t.HasCheckConstraint("CK_host_keys_1", "host_type_key IS NULL OR host_type_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("integration_sync_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("integration_sync_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_integration_sync_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("invoice_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("invoice_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_invoice_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("job_priorities", b =>
                {
                    b.Property<string>("priority_key")
                        .HasColumnType("text")
                        .HasColumnName("priority_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("priority_key");

                    b.HasIndex("created_at");

                    b.HasIndex("priority_key");

                    b.ToTable("job_priorities", null, t =>
                        {
                            t.HasCheckConstraint("CK_job_priorities_0", "priority_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("job_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("job_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_job_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("job_types", b =>
                {
                    b.Property<string>("job_type_key")
                        .HasColumnType("text")
                        .HasColumnName("job_type_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("handler")
                        .HasColumnType("text")
                        .HasColumnName("handler");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("job_type_key");

                    b.HasIndex("created_at");

                    b.HasIndex("job_type_key");

                    b.ToTable("job_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_job_types_0", "job_type_key ~ '^[a-z0-9_.-]+$'");
                        });
                });

            modelBuilder.Entity("lead_outcomes", b =>
                {
                    b.Property<string>("outcome_key")
                        .HasColumnType("text")
                        .HasColumnName("outcome_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("outcome_key");

                    b.HasIndex("created_at");

                    b.HasIndex("outcome_key");

                    b.ToTable("lead_outcomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_lead_outcomes_0", "outcome_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("lead_priorities", b =>
                {
                    b.Property<string>("priority_key")
                        .HasColumnType("text")
                        .HasColumnName("priority_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("priority_key");

                    b.HasIndex("created_at");

                    b.HasIndex("priority_key");

                    b.ToTable("lead_priorities", null, t =>
                        {
                            t.HasCheckConstraint("CK_lead_priorities_0", "priority_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("lead_sources", b =>
                {
                    b.Property<string>("source_key")
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("source_key");

                    b.HasIndex("created_at");

                    b.HasIndex("source_key");

                    b.ToTable("lead_sources", null, t =>
                        {
                            t.HasCheckConstraint("CK_lead_sources_0", "source_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("lead_stages", b =>
                {
                    b.Property<string>("stage_key")
                        .HasColumnType("text")
                        .HasColumnName("stage_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("stage_key");

                    b.HasIndex("created_at");

                    b.HasIndex("stage_key");

                    b.ToTable("lead_stages", null, t =>
                        {
                            t.HasCheckConstraint("CK_lead_stages_0", "stage_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("path_anchors", b =>
                {
                    b.Property<string>("anchor_key")
                        .HasColumnType("text")
                        .HasColumnName("anchor_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("anchor_key");

                    b.HasIndex("anchor_key");

                    b.HasIndex("created_at");

                    b.ToTable("path_anchors", null, t =>
                        {
                            t.HasCheckConstraint("CK_path_anchors_0", "anchor_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("path_types", b =>
                {
                    b.Property<string>("type_key")
                        .HasColumnType("text")
                        .HasColumnName("type_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("type_key");

                    b.HasIndex("created_at");

                    b.HasIndex("type_key");

                    b.ToTable("path_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_path_types_0", "type_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("payment_methods", b =>
                {
                    b.Property<string>("method_key")
                        .HasColumnType("text")
                        .HasColumnName("method_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("method_key");

                    b.HasIndex("created_at");

                    b.HasIndex("method_key");

                    b.ToTable("payment_methods", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_methods_0", "method_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("payment_processors", b =>
                {
                    b.Property<string>("processor_key")
                        .HasColumnType("text")
                        .HasColumnName("processor_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("processor_key");

                    b.HasIndex("created_at");

                    b.HasIndex("processor_key");

                    b.ToTable("payment_processors", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_processors_0", "processor_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("payment_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("payment_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("person_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("person_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_person_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("project_phases", b =>
                {
                    b.Property<string>("phase_key")
                        .HasColumnType("text")
                        .HasColumnName("phase_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("phase_key");

                    b.HasIndex("created_at");

                    b.HasIndex("phase_key");

                    b.ToTable("project_phases", null, t =>
                        {
                            t.HasCheckConstraint("CK_project_phases_0", "phase_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("project_priorities", b =>
                {
                    b.Property<string>("priority_key")
                        .HasColumnType("text")
                        .HasColumnName("priority_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("priority_key");

                    b.HasIndex("created_at");

                    b.HasIndex("priority_key");

                    b.ToTable("project_priorities", null, t =>
                        {
                            t.HasCheckConstraint("CK_project_priorities_0", "priority_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("project_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("project_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_project_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("role_scopes", b =>
                {
                    b.Property<string>("scope_key")
                        .HasColumnType("text")
                        .HasColumnName("scope_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("scope_key");

                    b.HasIndex("created_at");

                    b.HasIndex("scope_key");

                    b.ToTable("role_scopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_role_scopes_0", "scope_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("roles", b =>
                {
                    b.Property<string>("role_key")
                        .HasColumnType("text")
                        .HasColumnName("role_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("role_key");

                    b.HasIndex("created_at");

                    b.HasIndex("role_key");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_roles_0", "role_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("service_packages", b =>
                {
                    b.Property<string>("package_key")
                        .HasColumnType("text")
                        .HasColumnName("package_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("default_price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("default_price");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("package_key");

                    b.HasIndex("created_at");

                    b.HasIndex("package_key");

                    b.ToTable("service_packages", null, t =>
                        {
                            t.HasCheckConstraint("CK_service_packages_0", "package_key ~ '^[A-Z0-9_\\-]+$'");

                            t.HasCheckConstraint("CK_service_packages_1", "default_price IS NULL OR default_price >= 0");
                        });
                });

            modelBuilder.Entity("slug_scopes", b =>
                {
                    b.Property<string>("scope_key")
                        .HasColumnType("text")
                        .HasColumnName("scope_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("scope_key");

                    b.HasIndex("created_at");

                    b.HasIndex("scope_key");

                    b.ToTable("slug_scopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_slug_scopes_0", "scope_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("square_customer_creation_sources", b =>
                {
                    b.Property<string>("source_key")
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("source_key");

                    b.HasIndex("created_at");

                    b.HasIndex("source_key");

                    b.ToTable("square_customer_creation_sources", null, t =>
                        {
                            t.HasCheckConstraint("CK_square_customer_creation_sources_0", "source_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("storage_providers", b =>
                {
                    b.Property<string>("provider_key")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<JsonElement?>("config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("provider_key");

                    b.HasIndex("created_at");

                    b.HasIndex("provider_key");

                    b.ToTable("storage_providers", null, t =>
                        {
                            t.HasCheckConstraint("CK_storage_providers_0", "provider_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("tags", b =>
                {
                    b.Property<string>("tag_key")
                        .HasColumnType("text")
                        .HasColumnName("tag_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("tag_key");

                    b.HasIndex("created_at");

                    b.HasIndex("tag_key");

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("CK_tags_0", "tag_key ~ '^[a-z0-9_\\-]+$'");
                        });
                });

            modelBuilder.Entity("work_item_priorities", b =>
                {
                    b.Property<string>("priority_key")
                        .HasColumnType("text")
                        .HasColumnName("priority_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("priority_key");

                    b.HasIndex("created_at");

                    b.HasIndex("priority_key");

                    b.ToTable("work_item_priorities", null, t =>
                        {
                            t.HasCheckConstraint("CK_work_item_priorities_0", "priority_key ~ '^[a-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("work_item_statuses", b =>
                {
                    b.Property<string>("status_key")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool?>("is_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<int>("sort_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("status_key");

                    b.HasIndex("created_at");

                    b.HasIndex("status_key");

                    b.ToTable("work_item_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_work_item_statuses_0", "status_key ~ '^[a-z0-9_]+$'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}


