// <auto-generated />
using System;
using MGF.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MGF.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215030327_ProjectMembers")]
    partial class ProjectMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MGF.Domain.Entities.Client", b =>
                {
                    b.Property<string>("CliId")
                        .HasColumnType("text")
                        .HasColumnName("cli_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CliId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.Person", b =>
                {
                    b.Property<string>("PerId")
                        .HasColumnType("text")
                        .HasColumnName("per_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initials");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PerId");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.Project", b =>
                {
                    b.Property<string>("PrjId")
                        .HasColumnType("text")
                        .HasColumnName("prj_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("archived_at");

                    b.Property<string>("CliId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DropboxUrl")
                        .HasColumnType("text")
                        .HasColumnName("dropbox_url");

                    b.Property<string>("FolderRelpath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folder_relpath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PathsRootKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paths_root_key");

                    b.Property<string>("PhaseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase_key");

                    b.Property<string>("PriorityKey")
                        .HasColumnType("text")
                        .HasColumnName("priority_key");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_code");

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<string>("TypeKey")
                        .HasColumnType("text")
                        .HasColumnName("type_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PrjId");

                    b.HasIndex("CliId");

                    b.HasIndex("PhaseKey");

                    b.HasIndex("PriorityKey");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.HasIndex("StatusKey");

                    b.HasIndex("TypeKey");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectCodeCounter", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("NextSeq")
                        .HasColumnType("integer")
                        .HasColumnName("next_seq");

                    b.HasKey("Year");

                    b.ToTable("project_code_counters", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<string>("PrjId")
                        .HasColumnType("text")
                        .HasColumnName("prj_id");

                    b.Property<string>("PerId")
                        .HasColumnType("text")
                        .HasColumnName("per_id");

                    b.Property<string>("RoleKey")
                        .HasColumnType("text")
                        .HasColumnName("role_key");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("released_at");

                    b.HasKey("PrjId", "PerId", "RoleKey", "AssignedAt");

                    b.HasIndex("PerId");

                    b.HasIndex("RoleKey");

                    b.HasIndex("PrjId", "PerId", "RoleKey")
                        .IsUnique()
                        .HasFilter("released_at IS NULL");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectPhase", b =>
                {
                    b.Property<string>("PhaseKey")
                        .HasColumnType("text")
                        .HasColumnName("phase_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("PhaseKey");

                    b.ToTable("project_phases", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectPriority", b =>
                {
                    b.Property<string>("PriorityKey")
                        .HasColumnType("text")
                        .HasColumnName("priority_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("PriorityKey");

                    b.ToTable("project_priorities", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectRole", b =>
                {
                    b.Property<string>("RoleKey")
                        .HasColumnType("text")
                        .HasColumnName("role_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("RoleKey");

                    b.ToTable("project_roles", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectStatus", b =>
                {
                    b.Property<string>("StatusKey")
                        .HasColumnType("text")
                        .HasColumnName("status_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("StatusKey");

                    b.ToTable("project_statuses", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectType", b =>
                {
                    b.Property<string>("TypeKey")
                        .HasColumnType("text")
                        .HasColumnName("type_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("TypeKey");

                    b.ToTable("project_types", (string)null);
                });

            modelBuilder.Entity("MGF.Domain.Entities.Project", b =>
                {
                    b.HasOne("MGF.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGF.Domain.Entities.ProjectPhase", null)
                        .WithMany()
                        .HasForeignKey("PhaseKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGF.Domain.Entities.ProjectPriority", null)
                        .WithMany()
                        .HasForeignKey("PriorityKey");

                    b.HasOne("MGF.Domain.Entities.ProjectStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGF.Domain.Entities.ProjectType", null)
                        .WithMany()
                        .HasForeignKey("TypeKey");
                });

            modelBuilder.Entity("MGF.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("MGF.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGF.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("PrjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MGF.Domain.Entities.ProjectRole", null)
                        .WithMany()
                        .HasForeignKey("RoleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
